version: "3.7"
services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "abc@abc.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - "9876:80"
    depends_on:
      - db

  # Redis
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbitmq:
    image: "docker.io/library/rabbitmq:management"
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: your_rabbitmq_user
      RABBITMQ_DEFAULT_PASS: your_rabbitmq_password

  # Website
  frontend:
    build:
      context: ./website/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
      - rabbitmq

  # # Go API
  api:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      GIN_MODE: release

volumes:
  postgres_data:
