# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-08T03:26:16Z"
  labels:
    app: passwordfortress
  name: passwordfortress
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_PASSWORD
      value: "12345"
    image: docker.io/library/postgres:latest
    name: postgres
    ports:
    - containerPort: 5432
      hostPort: 5432
    - containerPort: 5672
      hostPort: 5672
    - containerPort: 80
      hostPort: 8000
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 80
      hostPort: 9876
    - containerPort: 15672
      hostPort: 15672
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: 78d92f2048f09ec0fa2503565b22194bd9eb21230cf35e6f2435aa9159f37ad7-pvc
  - image: localhost/passwordfortress_frontend:latest
    name: frontend
  - image: localhost/passwordfortress_api:latest
    name: api
  - env:
    - name: PGADMIN_DEFAULT_PASSWORD
      value: PgAdmin2023
    - name: PGADMIN_DEFAULT_EMAIL
      value: abc@abc.com.br
    image: docker.io/dpage/pgadmin4:latest
    name: pgadmin
    securityContext: {}
    volumeMounts:
    - mountPath: /var/lib/pgadmin
      name: 6bca1025636d3c43f5ba9409f8e55533606735d32f3f3604c28a29fb1de7d0b1-pvc
  volumes:
  - name: 78d92f2048f09ec0fa2503565b22194bd9eb21230cf35e6f2435aa9159f37ad7-pvc
    persistentVolumeClaim:
      claimName: 78d92f2048f09ec0fa2503565b22194bd9eb21230cf35e6f2435aa9159f37ad7
  - name: 6bca1025636d3c43f5ba9409f8e55533606735d32f3f3604c28a29fb1de7d0b1-pvc
    persistentVolumeClaim:
      claimName: 6bca1025636d3c43f5ba9409f8e55533606735d32f3f3604c28a29fb1de7d0b1

